# Generated by Django 3.0.7 on 2020-06-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transactionlog_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=14),
        ),
    ]
